export const data: { [key: string]: any } = {
  numbers: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
  ],
  "zoom things": [
    "(children noises in the background)",
    "hello, Hello?",
    "i need to jump in another call",
    "can everyone go on mute",
    "could you please get closer to the mic",
    "(loud painful echo / feedback)",
    "next slide please",
    "can we take this offline",
    "could you share this slides afterwards",
    "can somebody grant presenter rights?",
    "can you email that to everyone",
    "sorry, i had problems logging in",
    "i need to go on mute",
    "sorry, i couldn't find the invite link",
    "i was having connection issues",
    "i need to go on mute",
    "i'll have to get back to you",
    "who just joined the meeting?",
    "do you see my screen?",
    "let's wait for tom",
    "sorry, i was on mute",
    "you will send the minutes?",
    "can you repeat please?",
    "let's sync after the meeting",
  ],
  "books and authors worth reading": [
    "The Great Gatsby",
    "Atlas Shrugged",
    "Atomic Habits",
    "Infinite Game",
    "The Beginning of Infinity",
    "48 Laws of Power",
    "Zero to One",
    "The Bitcoin Standard",
    "Rich Dad Poor Dad",
    "Naval Ravikant",
    "Simon Sinek",
    "David Deutsch",
    "Black Swan",
    "Antifragile",
    "The Lean Startup",
    "The 7 Habits of Highly Effective People",
    "Hero with a Thousand Faces",
    "Joseph Campbell",
    "Dostoevsky",
    "Rainer Maria Rilke",
    "James Joyce",
    "Umberto Eco",
    "İsmet Özel",
    "Carl Gustav Jung",
  ],
}
